### PR TITLE
Update sv.json

### PR DESCRIPTION
**Pull request by Agata-Gimi**
Fix of langkeys in story 11.4 because of incorrect number. (displaying as missing text in screen.

### CODE REVIEW

**Comment by mekwall** [comment]
@Agata-Gimi The test is failing for this PR since it's missing the following keys for Norwegian:

- `school_story_11.4_screen_5_title`
- `school_story_11.4_screen_5_button_1_title`
- `school_story_11.4_screen_5_button_2_title`

**Review by mekwall — CHANGES_REQUESTED** [review]
@Agata-Gimi The test is failing for this PR since it's missing the following keys for Norwegian:

- `school_story_11.4_screen_5_title`
- `school_story_11.4_screen_5_button_1_title`
- `school_story_11.4_screen_5_button_2_title`

**Comment by gimi-anders** [comment]
The changes in this PR needs to be done in all languages if the build should pass

**Review by gimi-anders — APPROVED** [review]

**Comment by gimi-anders** [comment]
> @Agata-Gimi The test is failing for this PR since it's missing the following keys for Norwegian:
> 
> * `school_story_11.4_screen_5_title`
> * `school_story_11.4_screen_5_button_1_title`
> * `school_story_11.4_screen_5_button_2_title`

This has now been fixed

**Review by mekwall — APPROVED** [review]

**Pull request merged**
